# Generated by Django 5.1.6 on 2025-03-01 18:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='created_by',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='participants',
        ),
        migrations.AddField(
            model_name='contest',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contest',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tags', models.JSONField(default=list)),
                ('difficulty', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField()),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='contests.contest')),
            ],
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
    ]
