# Generated by Django 5.1.6 on 2025-03-01 18:35

import datetime
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_rename_created_by_contest_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='end_time',
            field=models.DateTimeField(default=django.db.models.expressions.CombinedExpression(models.F('start_time'), '+', models.Value(datetime.timedelta(seconds=7200)))),
        ),
    ]
