# Generated by Django 5.1.6 on 2025-03-02 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_alter_contest_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestproblem',
            old_name='difficulty',
            new_name='codeforces_id',
        ),
        migrations.RemoveField(
            model_name='contestproblem',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='contestproblem',
            name='url',
        ),
        migrations.AddField(
            model_name='contestproblem',
            name='index',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contestproblem',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.contest'),
        ),
        migrations.AlterField(
            model_name='contestproblem',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
