# Generated by Django 5.1.6 on 2025-03-02 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_rename_difficulty_contestproblem_codeforces_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestproblem',
            name='name',
        ),
    ]
