# Generated by Django 5.1.6 on 2025-03-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_remove_contestproblem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='is_private',
        ),
        migrations.AddField(
            model_name='contest',
            name='problems',
            field=models.ManyToManyField(related_name='custom_contests', to='contests.contestproblem'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contestproblem',
            name='codeforces_id',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='contestproblem',
            name='contest',
        ),
        migrations.AddField(
            model_name='contestproblem',
            name='contest',
            field=models.ManyToManyField(blank=True, to='contests.contest'),
        ),
    ]
