# Generated by Django 5.1.6 on 2025-03-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_contest_participants_alter_contest_problems_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestproblem',
            name='problem_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
